# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170305_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='publiser',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
